import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Login.module.css'
import Link from 'next/link'

import { FcGoogle } from 'react-icons/fc'
import { AiFillGithub } from "react-icons/ai";
import { FaTwitter, FaFacebookSquare } from "react-icons/fa"

// React Toastify
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { account } from '@/appwrite/appwriteConfig'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

export default function Login() {

  const [email, setEmail] = useState()
  const [password, setPassword] = useState()
  const router = useRouter()

  useEffect(() => {
    const user = account.get()
    user.then(
      (response) => {
        router.push("/dashboard")
      },
      (err) => {
        console.log(err)
      }
    )
  }, [router])

  function handleInputChange(event) {
    const eventFrom = event.target.id

    if (eventFrom === "email") {
      setEmail(event.target.value)
    } else if (eventFrom === "password") {
      setPassword(event.target.value)
    }
  }

  async function submitForm(e) {
    e.preventDefault();
    try {
      await toast.promise(
        () => loginUser(),
        {
          pending: 'Logging In User',
          success: 'Logged User Sucessfully 👌',
          error: 'Operation Failed 🤯',
        }
      );
    } catch (error) {
      console.error("An error occurred:", error);
      toast.error(String(error));
    }
  }

  async function loginUser() {
    try {
      const response = await account.createEmailSession(email, password);
      router.push("/dashboard")
      if (response.err) {
        throw new Error(response.err);
      }
    } catch (error) {
      throw error;
    }
  }
  return (
    <>
      <Head>
        <title>Login Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main className={styles.loginContainer}>
          <div className={styles.loginForm}>
            <Image src={"/logo.png"} alt={"logo"} width={80} height={80} />
            <h1>Welcome To Sensory-Cademy</h1>
            <p>Login Via Email Or Social Handles</p>
            <form className={styles.formInput} onSubmit={submitForm}>
              <div className={styles.socialHandles}>
                <button><FcGoogle /></button>
                <button><Image src={"/linkedin.svg"} alt='linkedin logo' className={styles.linkedin} width={22} height={22} /></button>
                <button><AiFillGithub /></button>
                <button><FaTwitter className={styles.twitter} /></button>
                <button><FaFacebookSquare className={styles.facebook} /></button>

              </div>
              <div className={styles.divider}>OR</div> {/* Divider with text */}
              <input
                type="email"
                placeholder="Enter Your Email"
                value={email}
                onChange={handleInputChange}
                id='email'
                required
                autoComplete="off"
              />
              <input
                type="password"
                placeholder="Enter Your Password"
                value={password}
                onChange={handleInputChange}
                id='password'
                required
                autoComplete="off"
              />
              <button className={styles.submit} type="submit">Log In</button>
              <p>Don't have an account yet ?? <Link href='/signUp'>Sign Up</Link></p>
            </form>
          </div>
        </main>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </main>
    </>
  )
}
